CREATE TABLE Employees ( 
  
ID INT NOT NULL AUTO_INCREMENT , 
Name VARCHAR(50) NOT NULL , 
Surname VARCHAR(50) NULL , 
Patronymic VARCHAR(50) NULL , 
Sex BIT NOT NULL , 
Age SMALLINT NULL , 
Passport VARCHAR(50) NOT NULL , 
Phone VARCHAR(50) NOT NULL , 
Position VARCHAR(50) NOT NULL ,
Education VARCHAR(50) NOT NULL , 
`Hiring date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP , 

PRIMARY KEY (`ID`) ,
CONSTRAINT check_employee CHECK (Age >= 18 AND `Hiring date` >= `01.01.2000`)
  
)

CREATE TABLE Documents (

ID INT NOT NULL AUTO_INCREMENT , 
`Type ID` INT NOT NULL , 
`Certification date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (`ID`),
FOREIGN KEY (`Type ID`) REFERENCES Types(ID) ON DELETE RESTRICT ON UPDATE CASCADE
  
)


CREATE TABLE Types ( 

ID INT NOT NULL AUTO_INCREMENT , 
Name VARCHAR(50) NOT NULL , 
Description VARCHAR(500) NOT NULL , 

PRIMARY KEY (`ID`) 
)

CREATE TABLE `Document preparation` {

ID INT NOT NULL AUTO_INCREMENT , 
`Employee ID` INT NOT NULL,
`Document ID` INT NOT NULL, 
Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (`ID`),
FOREIGN KEY (`Document ID`) REFERENCES Documents(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (`Employee ID`) REFERENCES Employees(ID) ON DELETE RESTRICT ON UPDATE CASCADE
)

CREATE TABLE `Document composition` {

ID INT NOT NULL AUTO_INCREMENT , 
`Employee ID` INT NOT NULL,
`Document ID` INT NOT NULL, 
Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (`ID`),
FOREIGN KEY (`Document ID`) REFERENCES Documents(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (`Employee ID`) REFERENCES Employees(ID) ON DELETE RESTRICT ON UPDATE CASCADE
)

